### ISSUE TITLE
[Documentation] ns-pill update

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#108]
### Outcome
Updated docs to reflect new colour options (and caveat link? TBC) at https://nucleus.design/docs/components/ns-pill#usage

### Scope
- [x] Update Markdown
- [x] PR
- [x] Merge

**Comment by RobTobias123** [comment]
To reflect changes made in  https://github.com/centrica-engineering/nucleus/issues/215 and https://github.com/centrica-engineering/nucleus/issues/196

**Comment by andij** [comment]
This Docs PR: https://github.com/centrica-engineering/nucleus-docs/pull/107 contains the new colour options and is part of the work undertaken here: https://github.com/centrica-engineering/nucleus/issues/196

We can certainly improve the docs further if we feel that it's missing something. The caveat link for example.

(I've never been a fan of the image in the Content guidance. It's not the right scale, it has the wrong typography, the spacing is weird and the typo is annoying.)

**Comment by RobTobias123** [comment]
I will keep this issue open to address those points Drew.
