### ISSUE TITLE
Rebuild the docs using Astro

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#215]
## Outcome

The Nucleus documentation rendered with [Astro](https://astro.build/) and [Starlight](https://starlight.astro.build/).

## Scope

- [x] Evaluate the existing Nucleus documentation and understand what's required
- [ ] Rebuild the docs specific components as required
  - colours.js
  - component-placement.js
  - page-footer.js
  - storybook-page.js
  - storybook-story.js
- [ ] Identify additional components that can help
- [ ] Code freeze on Nucleus Docs to perform the migration
- [ ] Refactor all documents
- [ ] Update README

**Comment by andij** [comment]
I have evaluated the process of re-platforming our docs to Astro and Starlight.

Here is the epic branch: https://github.com/centrica-engineering/nucleus-docs/tree/epic/replatform-astro

It's proven to be straightforward and requires a few 'find and replace' tasks across all documents. For example:

- Update the frontmatter 'title'
- Relocate the assets
- Remove `.md` from any docs links
- Move the imports to frontmatter

I expect that some of the docs components markup can be reused.

**Comment by PtitBen** [comment]
Astro has been set up. 
[An Epic for the new docs has been created](https://github.com/centrica-engineering/nucleus-docs/issues/243)
