### ISSUE TITLE
Component content from JSDocs

### ISSUE THREAD

**Issue by PtitBen** [centrica-engineering/nucleus-docs#246]
## Outcome
We pull content automatically from the components' codebase into the documentation.

## Scope

The following content blocks: 
- [x] Name
- [x] Main purpose
- [x] Specifications
- [x] Events
- [x] Permitted tags for slot
- [ ] Component placement - list of components
- [x] Component display name
- [x] Component categories [`Form`, `Experience`]
- [x] Component flags [`internal`, `deprecated`]

**Comment by MekalaNagarajan-Centrica** [comment]
## Permitted Tags
Jsdoc and web component analyzer support permitted tags for a slot as shown below.

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78729952/91e3ad55-59e1-476c-83ab-89df3b8f3b09)

When the custom elements are analysed and transformed into JSON format, the permitted tags are not included.

```json
  "slots": [
    {
      "name": "heading",
      "description": "The heading of the accordion."
    },
    {
      "description": "Anonymous slot for expanders."
    }
  ]
```

**Comment by MekalaNagarajan-Centrica** [comment]
PR to update jsdoc https://github.com/ConnectedHomes/nucleus/pull/3333. This includes
- Component display name
- Component category
- Component `internal` flag

**Comment by MekalaNagarajan-Centrica** [comment]
Update sidebar using jsdoc https://github.com/centrica-engineering/nucleus-docs/pull/292

**Comment by MekalaNagarajan-Centrica** [comment]
This ticket can be closed as the below work are moved to individual tickets.
`@placement` updation is moved to  https://github.com/centrica-engineering/nucleus-docs/issues/364
`description` updation is moved to https://github.com/centrica-engineering/nucleus-docs/issues/363
