### ISSUE TITLE
[discovery] Interaction

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#279]
#### Understand what interactive elements could be fun to include in Nucleus Docs.

Interactive elements may increase engagement with the docs by helping explain concepts, features or benefits.
We could guide users through the docs interactive storytelling or games or motivate them to learn more.

### Scope

- [x] Identify types of interactions we could explore
- [x] Brainstorm, without prejudice research and consider how we might apply these to the Nucleus Docs to meet the desired outcome.
- [x] Share this work with the team and encourage them to be involved. 
- [x] Converge to filter the best ideas.
- [x] Apply to any design iterations for Docs.

**Comment by RobTobias123** [comment]
Set up Miro board on Nucleys Teams Astro Chat and added my comments, images, links and references, initially created in Figma so that both Drew and Mekala can take part in ideation. LInk to the Miro: https://teams.microsoft.com/l/entity/8216e453-3db5-48ee-a3d6-5122f505c8a3/_djb2_msteams_prefix_1441442193?context=%7B%22subEntityId%22%3Anull%2C%22chatId%22%3A%2219%3A7510e676ebde4fd3b4a2ac968c61d3df%40thread.v2%22%2C%22contextType%22%3A%22chat%22%7D&tenantId=a603898f-7de2-45ba-b67d-d35fb519b2cf&allowXTenantAccess=false

**Comment by RobTobias123** [comment]
Screenshots of the brainstorm ideas and research so far for interaction discovery:

![Screenshot 2023-12-19 at 16 38 15](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/faaadf0b-7f7d-42bc-8baf-f72a0082768a)

![Interactive elements](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/d4b9c4de-5c67-4d63-bb52-f55b5ff84b72)

**Comment by RobTobias123** [comment]
Search results page best practices article: https://uxplanet.org/best-practices-for-search-results-1bbed9d7a311

We need to ensure our Docs search results are relevant, trusted and easily understood.

**Comment by RobTobias123** [comment]
TOC RHS desktop visual application of concept shared 22 Dec (on right):

![Screenshot 2023-12-28 at 12 24 58](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/1f4611ee-7207-46ae-9821-8363193a8d24)

**Comment by RobTobias123** [comment]
Alternative, simpler version of the TOC, that doesn't cover more than 1 (ie. not parent+chid) and removed the orange highlight part. This is my preference - prominence is less than above version:

![Screenshot 2023-12-28 at 12 29 18](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/23ad6cb8-be7b-43aa-b97b-968a99e18590)

**Comment by RobTobias123** [comment]
As requested in the last meeting, I have mocked-up a more static width LHS menu, with collapsible expanders as an alternative concept to the sliding side drawer/top level icons approach seen in most of the designs so far. This could perhaps be simpler to implement:

![Screenshot 2023-12-28 at 13 00 46](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/7c1e9fba-6b35-4a57-ab0a-73d05d0c0795)

**Comment by RobTobias123** [comment]
Based on Drew's suggestion, I've explored a couple of alternative RHS Column approaches that keep the RHS nearer the top for prominence. My preference would be version B because it 'belongs' to the page title/masthead so to me it feels the most correctly placed of the two in terms of content hierarchy. It also provides more width for longer component names for eg. ns-appointment-picker -  the downside is it is not much higher than the main design and causes a visual 'step' and and less room for H2 link buttons in the horizontal space.

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/5fe1f93a-dd86-4470-8cf8-9f5838a33a3a)

**Comment by andij** [comment]
## 404 page idea

Can we take the URL that results in a 404 and provide relevant links to pages within the Docs?

**Comment by RobTobias123** [comment]
### Discovery for Example snippet interactions

As emphasised yesterday it is considered important to have some way to configure or modify the code snippet examples we will be utilising in the new docs. Exploring this further, there are a couple of directions we could take...

1. Link from the snippet to a new browser tab to a 'Play/Try it out' type area and have a form-based interaction displaying the results in a code and preview window. Or...
2. Link from the snippet to a new browser tab to a 'Play/Try it out' type area but instead of a form have direct editing capability from the code window.

#### Benefits of using a separate window for this... 

- Focuses the user on the task in hand in its own dedicated space with minimal distraction/large real estate.
- Allows easy reference of the parent docs info/spec/other pages whilst configuring.
- Provides the user with a way to check their ideas quickly in docs environment, understand what they can change in a visual way, and copy results to a Playground prototype. (Matching known use cases of Storybook).
- Draws parallels with code helper on Playground and familiar pattern as seen on W3 Schools, MDN Docs etc.
- The form part in Route 1 can be created using JSDocs (ask Jon)

Here are initial example mock-ups of both intentions (my preference is route 1 as this will be familiar to those who used Storybook in this way, and more 'beginner-friendly' for the less code-aware). 

#### Route 1: 
Example default is still shown and 'copy-able' from the doc page. There is a 'Try it out' button bottom right of it. (words and icon TBC)...
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/92abe821-0c56-4ca9-93b9-2a7ffe301c6f)

On clicking the button we'd see a new browser tab open like this. It shows the code and preview side by side, a reminder of teh component name top left (like seen in Playground) and reuse of the button bar style for the 3 functions: Configure, Run, Reset. Reset returns everything to the default, Run takes the configuration settings and applies them to the preview, Configure shows or hides the form section that allows the user to configure options and content...

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/f3e6b0ae-0285-492f-b801-bfeefc3600dc)
...config open...
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/c73685e1-febe-4a88-8934-605d4810d2d8)

The user will still be able to copy the snippet in the same way as they could from the example on the parent doc page - the button top right on the code window. This might be beneficial to expand on hover to display label 'copy snippet'.

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/324675a4-0ca8-4d61-b59a-137bf3a78422)


#### Route 2: 
Same initial step as route 1, but without the Configure function and button. This route would require more 'HTML dexterity' of the user, and also it doesn't offer much over performing the same task in Playground. Even though it may be simpler for us to implement. (Hence my preference for Route 1).

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/3a2c669c-c094-4f3f-872e-ce1d716d7169)

### Further considerations

- How might the windows/layout best scale? Route 1 config when open may push the example code down a long way, however the example code and preview are likely to be related in length too so might not be such an issue. 

- How can this work at mobile viewports? (check places like Storybook and other DS like Salesforce Lightning etc to see how they handle this)
- Should we add a viewport size selector?
- There are 2 clear categories of configuration - 1 = Global items such as simulating the panel decoration colour and viewport sizes, 2 = Component specific items that can be changed. A question may be should these be clearly grouped in the UI or seen as all part of the same config options?

**Comment by RobTobias123** [comment]
### Masthead behaviour on scroll exploration

It was observed that the current implementation of the new masthead design take up a lot of real estate on the page, and the minimalisation or loss of the masthead after initial view would be beneficial to give more space to the content which by then has more importance to the user...

#### A few ideas explored...

Main masthead on scroll goes up with page until out of view...

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/7675e5e6-5e7f-4b01-8a01-c3ed83e7c9a4)
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/1d090172-41de-4786-8146-5bf379e7215e)

**Concept 1:** Minimalised masthead strip then sticks to top with tab buttons...
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/2fb067db-5a10-40c9-bcd8-467aaa14f76b)

**Concept 2:** Masthead is prefixed to the tab buttons to allow for more content height on page but then reduces horizontal space for the buttons...
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/8991d40f-9804-44b7-bb3f-d1ed10972fbd)

What if it was permitted to have more buttons than space? We could add a chevron to the RHS to allow showing of the next set and back (a fairly common pattern)...
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/2dc80878-084b-4bfa-896a-5cc77745ee28)
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/28e4683f-83c4-4392-8f86-65aa49d66332)


**Concept 3:**  Lose the masthead completely on scroll and only stick the tab buttons to the top. ie. do we even need the masthead after it has scrolled past as it should be apparent which page you are on from a) the LHS menu, b) what you clicked to get there, and c) you can always scroll back up to the top/click Overview if you aren't sure. This is my **preferred route** as I don't think  it will prove necessary to display the masthead past the initial view. 

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/30812fd8-3258-4f6b-af59-20750b45ead0)

**Comment by RobTobias123** [comment]
Transition animations (micro-interactions) for the tab buttons, suggested:

Tab buttons transition animation example of intent: https://www.figma.com/proto/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?page-id=0%3A1&type=design&node-id=137-12886&viewport=-9396%2C-43874%2C0.81&t=oJkAhwyi7r3hdDWU-1&scaling=min-zoom&starting-point-node-id=137%3A12745&mode=design
 
Spec for that is: 
// After delay
animation-delay: 1000ms;
// Navigate to: "[Next right]";
// Animate: Dissolve;
animation-timing-function: ease-in-out;
animation-duration: 1000ms;
