### ISSUE TITLE
Masthead

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#295]
## Outcome

Masthead component implemented and styled.

## Scope

- [x] Build the Masthead
- [x] Reorganise the layout of `TwoColumnContent.astro`
- [x] Styling

## References

- #287

**Comment by andij** [comment]
Reorganise the layout of Starlight to allow is to include the Masthead.

- [x] Hide the default `PageTitle.astro` in Starlight
- [x] Create our own `NucleusPageTitle.astro` component
- [x] Place `NucleusPageTitle.astro` in `TwoColumnContent.astro`

**Comment by andij** [comment]
- #290

**Comment by RobTobias123** [comment]
#287

**Comment by andij** [comment]
There appears to be a difference with the CSS in the build compared to local development. This will fix the spacing/sizing issue of the masthead SVG that is only apparent in the build.

**Comment by RobTobias123** [comment]
Dimensions: https://github.com/centrica-engineering/nucleus-docs/issues/280#issuecomment-1889353819

**Comment by andij** [comment]
PR for improvements following interim showcase on 2024-01-11
- #305
