### ISSUE TITLE
Section tabs

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#296]
## Outcome

Section tabs component implemented and styled.

## Scope

- [x] Build the Section tabs
- [x] Include in the Masthead component
- [x] Styling
- [x] Transition

## References

- #289

**Comment by RobTobias123** [comment]
#289

**Comment by andij** [comment]
- #298

**Comment by RobTobias123** [comment]
Transitions - https://github.com/centrica-engineering/nucleus-docs/issues/279#issuecomment-1889336919

**Comment by andij** [comment]
- #311
