### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#297]
## Outcome

Layout changes implemented and styled.

## Scope

- [x] Two column content responsive behaviour

**Comment by RobTobias123** [comment]
Following today's discussion regarding defining the responsive behaviour of the layout at desktop sizes...
I have suggested responsive behaviour mock-up from 1152 narrow, 1620 (approx. most design iterations so far) and very wide 2500. It may be beneficial also to drop the H1 size at the smaller viewport breakpoint if feasible. I will mock up a suggestion for the tabs part tomorrow as if there were more and how that would behave:

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/befd5f80-bc55-4d71-9d14-6f915c02d7f2)
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/b41de174-fdaf-4735-862b-8aa19de09f5b)
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/c9db5456-e962-4295-afea-bf26da3200f7)

**Comment by RobTobias123** [comment]
Looking at the responsive layout when it gets to Mobile - I've taken screenshots of a component page from my iPhone 8 (small screen) and overlaid comments in situ on the Figma working file. Please take a look:

https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=170%3A13916&mode=design&t=CuRsQe0iMWDomhuQ-1

**Comment by andij** [comment]
I've modified the desktop layout as best as I can to fit the designs.
