### ISSUE TITLE
Integrate Algolia search

### ISSUE THREAD

**Issue by MekalaNagarajan-Centrica** [centrica-engineering/nucleus-docs#309]
## Outcome
To integrate the doc search with the Algolia search application.
### Scope
- [x] starlight docsearch integration
- [ ] customization
  - [ ] Search component
  - [ ] search dialog

**Comment by MekalaNagarajan-Centrica** [comment]
Customization of search dialog and search result page will be done after the release of docs into production.

**Comment by PtitBen** [comment]
We'll go live with Algolia.
Compare with Starlight and decide on a winner. 

Advantages of Starlight: 
- It builds with the docs
- no need to maintain

So chances are we stick with starlight.
