### ISSUE TITLE
Asides

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#310]
## Outcome

Aside component styling.

## Scope

- [x] Styling
- [x] Colours

## References

- #294

**Comment by RobTobias123** [comment]
Note the latest styling concept of using rounded corners on the RHT and RHB to better compliment the other items...
https://github.com/centrica-engineering/nucleus-docs/issues/294#issuecomment-1892316348

**Comment by RobTobias123** [comment]
Following our conversation today I will be looking to create and provide a whole set of colour values based on the High/Main/Low colour variants and how they are applied through starlight, and using appropriate existing Nucleus Hues. (See props.css and custom.css for current values). 

Each set needs to have a Light and Dark mode equivalent and a correlation between the saturation and lightness where possible. (They must also meet WCAG contrast ration requirements so they may need to be flexible).

**Comment by RobTobias123** [comment]
There has been considerable effort today to get the colours working for the asides utilising a pattern for both dark and light modes and ensuring contrast ratios. 

All asides described use the same existing  Nucleus **Hues**. 

#### Light mode asides use:

- Light = variant for the background (all with  Sat: [inherited from main colour],  Light 97%).
- Mid =  existing main  colour  for heading/icon/keyline (existing eg. ‘Indigo’)- (all with  Sat: [inherited from main colour],  Lightness [inherited from main colour]).
- Dark = variant for the background (all with  Sat: [inherited from main colour],  Lightness 23%).
- Paragraph = existing Navy main colour

#### Dark mode asides use:

- Light = variant for the background (all with  Sat: [inherited from main colour],  Lightness 97%).
- Mid =  variant  colour for heading/icon/keyline (all with  Sat: [inherited from main colour],  Lightness 66%).
- Dark = variant for the background (all with  Sat: [inherited from main colour],  Lightness 16%).
- Paragraph = existing White main colour

#### Here's my suggested set of HSL values as a conclusion:

## LIGHT MODE
### Notes 
(WCAG 8.17:1)

```
--ns-hue-indigo: 223;
-ns-color-indigo-high: hsl(var (--ns-hue-indigo), 43%, 97%) ;
-ns-color-indigo: hsl(var (--ns-hue-indigo), 43%, 35%);
-ns-color-indigo-low: hsl(var (--ns-hue-indigo), 43%, 23%) ;
```


### Tips 
(WCAG 8.6:1)

```
--ns-hue-purple: 273;
-ns-color-purple-high: hsl(var (--ns-hue-purple), 43%, 97%) ;
-ns-color-purple: hsl(var (--ns-hue-purple), 43%, 35%);
-ns-color-purple-low: hsl(var (--ns-hue-purple), 43%, 23%) ;
```


### Caution 
(WCAG 4.6:1)

```
--ns-hue-orange: 17;
-ns-color-orange-high: hsl(var (--ns-hue-orange), 74%, 97%) ;
-ns-color-orange: hsl(var (--ns-hue-orange), 74%, 43%);
-ns-color-orange-low: hsl(var (--ns-hue-orange), 74%, 23%) ;
```


### Danger / Don’t 
(WCAG 5.52:1)

```
--ns-hue-red: 348;
-ns-color-red-high: hsl(var (--ns-hue-red), 99%, 97%) ;
-ns-color-red: hsl(var (--ns-hue-red), 99%, 39%);
-ns-color-red-low: hsl(var (--ns-hue-red), 99%, 23%) ;
```


### Do 
(WCAG 4.61:1)

```
--ns-hue-green: 151;
-ns-color-green-high: hsl(var (--ns-hue-green), 43%, 97%) ;
-ns-color-green: hsl(var (--ns-hue-green), 43%, 35%);
-ns-color-green-low: hsl(var (--ns-hue-green), 43%, 23%) ;

```

## DARK MODE

### Notes
(WCAG 5.56:1)

```
--ns-hue-indigo: 223;
-ns-color-indigo-high: hsl(var (--ns-hue-indigo), 43%, 97%) ;
-ns-color-indigo: hsl(var (--ns-hue-indigo), 43%, 66%);
-ns-color-indigo-low: hsl(var (--ns-hue-indigo), 43%, 16%) ;
```


### Tips 
(WCAG 5.34:1)

```
--ns-hue-purple: 273;
-ns-color-purple-high: hsl(var (--ns-hue-purple), 43%, 97%) ;
-ns-color-purple: hsl(var (--ns-hue-purple), 43%, 66%);
-ns-color-purple-low: hsl(var (--ns-hue-purple), 43%, 16%) ;
```



### Caution 
(WCAG 5.84:1)

```
--ns-hue-orange: 17;
-ns-color-orange-high: hsl(var (--ns-hue-orange), 74%, 97%) ;
-ns-color-orange: hsl(var (--ns-hue-orange), 74%, 66%);
-ns-color-orange-low: hsl(var (--ns-hue-orange), 74%, 16%) ;
```



### Danger / Don’t 
(WCAG 4.91:1)

```
--ns-hue-red: 348;
-ns-color-red-high: hsl(var (--ns-hue-red), 99%, 97%) ;
-ns-color-red: hsl(var (--ns-hue-red), 99%, 66%);
-ns-color-red-low: hsl(var (--ns-hue-red), 99%, 16%) ;
```


### Do 
(WCAG 6.71:1)

```
--ns-hue-green: 151;
-ns-color-green-high: hsl(var (--ns-hue-green), 43%, 97%) ;
-ns-color-green: hsl(var (--ns-hue-green), 43%, 66%);
-ns-color-green-low: hsl(var (--ns-hue-green), 43%, 16%) ;

```
See the figma visual here: https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=450%3A7725&mode=design&t=ICP3VsByB7zknKaS-1

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/f915f86f-f029-46ef-9110-2a791f715a28)

**Comment by RobTobias123** [comment]
Also, please note that due to the keyline LHS style, the Corner Radii only applies to the top right and bottom right:
`border-radius: 0px 10px 10px 0px;`

**Comment by RobTobias123** [comment]
Here's a shot of the method used to define the colours, (3-4 other methods were explored but Iteration 1 works best and was used as a basis for the final colours - although the lightness values were altered very slightly from this across hues to achieve the desired contrast ratios.

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/447eebee-cb6c-4f0d-8331-22981fd0a5d7)

**Comment by andij** [comment]
All the colours of the Asides have been implemented.

- #381 

To showcase the Asides I've added a file `ns-test.mdx` which includes content to showcase some of the UI and how some content renders.

Here's the deep-link to the Asides: https://feature-aside-styles.nucleus-docs.pages.dev/components/ns-test/#asides
