### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#316]
## Outcome

The Docs page footer.

## Scope

- [x] Build the page footer component
- [x] Styling

## Reference

- #314

**Comment by andij** [comment]
- #319

**Comment by andij** [comment]
The component and styling for the Footer have been created.

We've discussed the need for an `<InlineLink />` component to allow us to pass the component name into the URL and set the configuration of the link attributes. And additionally include an icon.

**Comment by RobTobias123** [comment]
I have left a comment on the PR about a potential direction for the exposed area at the bottom. I will look into that to see if it could work.
