### ISSUE TITLE
Configure Example

### ISSUE THREAD

**Issue by MekalaNagarajan-Centrica** [centrica-engineering/nucleus-docs#320]
## Outcome
To understand the approach to create the example configure page.
(discovery work from Rob: https://github.com/centrica-engineering/nucleus-docs/issues/303)
### Scope
- [x] Create a form with attributes and slots for a given component.
- [x] Transfer the example html from the component page to the configure page
- [x] Rendering the configuration change
- [x] Update the configuration change in the code snippet
- [x] Styling the configure page
- [x] Viewports

**Comment by MekalaNagarajan-Centrica** [comment]
PR https://github.com/centrica-engineering/nucleus-docs/pull/327

ExampleView which takes a `template` slot for the html has to be changed to accept a `src` attribute for the example html page. This will help to get the html content in Configure page.

**Comment by MekalaNagarajan-Centrica** [comment]
`_examples` within docs has limit the file navigation when we build the docs. It would be good to move them to assets.

**Comment by RobTobias123** [comment]
Here's the form inputter styles **suggestion** for configuration options: https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=279%3A5192&mode=design&t=T367BSaTQr4S3o4j-1

**Comment by RobTobias123** [comment]
⁠
@MekalaNagarajan-Centrica 

Following our discussion yesterday - here's a couple of more refined layout designs for the configurator and parent page example. 

My preference is leaning towards B as the viewport and scale are secondary actions to actually seeing the preview so hierarchy and grouping feels better. 

Also included is how things could work with the tabbed examples. 

The Config page itself has been designed as a 'split' page with defined areas. LHS = configuration form, RHS = the effect that has on the Preview and code. The run and reset (visual emphasis applied to Run - main action, and less on reset as a minor action) are grouped with the config. The viewport and scale grouped with the preview, and of course the copy code button would show as it does on the snippet section. All sections are clearly labelled.

We also now have the name as a mini/namespace-masthead in the top right to optimise space.

The form is always open in the config window (not hidden like earlier iterations) as this I think is the main task people will be coming here for. 

Responsiveness: I envisage whichever side appears longest to stretch the other side out - so if LHS Config options are many the preview and snippet would still take 50% of the vertical space up each on the RHS. If the preview was long eg, ns-timeline, then the snippet would become the same length and the height of the grey LHS config panel would stretch down to meet it at the bottom edge even if the config form elements are only a few (pin to the top and the run and reset buttons stay with form).

Let me know if any changes etc. Next, I can provide you with the SVGs.

### Example A (High-level preview options)

https://www.figma.com/file/1raWkMB6pKTBDB30OgSjgp/320---Configure-example-layouts?type=design&node-id=1%3A212&mode=design&t=PBqslnf9DAf3rIb8-1

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/1f5cc452-9bb8-45d7-a000-216fa79957f8)


### Example B (Low-level preview options - my preference)

https://www.figma.com/file/1raWkMB6pKTBDB30OgSjgp/320---Configure-example-layouts?type=design&node-id=4%3A2119&mode=design&t=PBqslnf9DAf3rIb8-1

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/91b8ab93-372b-4dbd-9591-e6bc70af0a73)

**Comment by RobTobias123** [comment]
Further conversations and design iterations have taken place today. Versions D & E are the most refined outcome of this. Please see notes in situ on items:

https://www.figma.com/file/1raWkMB6pKTBDB30OgSjgp/320---Configure-example-layouts?type=design&node-id=0%3A1&mode=design&t=OuBy26giECTPDH6d-1

**Comment by andij** [comment]
- #380

**Comment by andij** [comment]
I've put together the first pass at styling the Configure button and the Viewport and Zoom: https://feature-configure-styles.nucleus-docs.pages.dev/components/ns-card/


And the Configurator: https://feature-configure-styles.nucleus-docs.pages.dev/configure/components/ns-card/standard/


I will pause on any additional work for now until Mekala is back. Here's a list of things I can think of right now:

- Use Roboto font
- Add logo
- Add theme switcher
- Anonymous slot is missing content
- Improve radio button styles
- Select drop-down for viewport and zoom instead of radio buttons

**Comment by MekalaNagarajan-Centrica** [comment]
We will go with mobile and desktop viewports and based on feedback we will add rest of the viewports (scope for future work).
