### ISSUE TITLE
Spec list

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#326]
## Outcome

Display the specification tables into description lists instead.

## Scope

- [x] Replace the `<table>` markup in `specification.astro` with `<dl>`
- [x] Integrate the `properties` into the same list as `attributes`
- [x] Decide on the most sensible content structure
- [x] Implement the additional tables (Slots, Events)

**Comment by andij** [comment]
- #325

**Comment by RobTobias123** [comment]
Here's the suggested fonts and styles applied to the same spec list - with 48px paragraph spacing and keylines. Just a suggestion using existing styles. https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=279%3A5416&mode=design&t=T367BSaTQr4S3o4j-1

**Comment by andij** [comment]
Here's the updated URLs for user testing:


Spec table:
https://feature-spec-table.nucleus-docs.pages.dev/components/ns-landmark/


Spec list:
https://feature-spec-list.nucleus-docs.pages.dev/components/ns-landmark/

**Comment by RobTobias123** [comment]
Here's the results analysis of significant findings and recommendations from the user testing:

https://github.com/centrica-engineering/nucleus-docs/issues/328#issuecomment-1927115024

**Comment by RobTobias123** [comment]
Summary based on the results of the user testing for specs...

- DL format worked best for High-volume data by a significant amount.

- Table format worked best for Low-volume data - though the difference was less.

**The recommendation is to proceed with using both styles as above.** 

(However, it should be considered if it may be of benefit to utilise the same format for both if it reduces complexity/maintenance effort etc. If that is the case I would suggest using DL for both.)

**Comment by andij** [comment]
- PR for the Specification list/table: https://github.com/centrica-engineering/nucleus-docs/pull/375

To check, take a look at these preview pages: 

- https://feature-specification.nucleus-docs.pages.dev/components/ns-accordion/#specification (both low volume)
- https://feature-specification.nucleus-docs.pages.dev/components/ns-card/#specification (both medium volume)
- https://feature-specification.nucleus-docs.pages.dev/components/ns-inputter/#specification (high volume for attributes also includes Events table)
