### ISSUE TITLE
Masthead - Choose the colour scheme

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#359]
### Outcome
A comprehensive list of the colours to apply to each section for the masthead backgrounds.

### Scope

- [x] Check existing implementation against original design intent provided
- [x] Check difference between sections is enough to be noticedcombined with other factors ie. form and namespace/category, Associated SVG etc.
- [x] Provide clear guidance and colour values based on palette we're using (hex/HSB) in this ticket.
- [ ] Check each area once implemented for any unforeseen issues.

**Comment by RobTobias123** [comment]
Masthead colour assignation - decided and checked for WCAG contrast compliance... https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=395%3A5189&mode=design&t=dOGDxhyUsSEKqgky-1

**Comment by RobTobias123** [comment]
![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/1cd4c926-9298-4723-bc55-5c26b2f3cc82)

**Comment by RobTobias123** [comment]
Updated Orange from Accent low to Nucleus 'Orange'. Contrast ratio compliant. Now looks better  like this:

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/232e45b6-30d2-48b1-b5e1-4756648075ef)

Colour Values:

Components: background: var(--Teal, #315B73);
Experiences: background: var(--Blue, #203374);
**Foundations: background: var(--Orange, #BF4B1C);**
Patterns: background: var(--Purple, #5D337F);
Page types: background: var(--Magenta, #9E326D);

**Comment by RobTobias123** [comment]
HSL conversions of the above colour values:

Components: 202/40/32
Experiences: 226/57/29
Foundations: 17/74/43
Patterns: 273/43/35
Page types: 327/52/41

**Comment by RobTobias123** [comment]
Considered a version for deprecated components using a modified set of values for Red to achieve contrast ratio requirements:

**Red:** 
Hex: #C60128
HSL:  348/99/39

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/2af005bf-d429-4387-bb66-07511ebfc51d)

**Comment by RobTobias123** [comment]
Exploring this idea further, there could be a need to choose a colour for the Form type components too:


### Concept 1: Use different colour backgrounds for deprecated and Form components.

Problem: Appending the bracketed word is a bit strong, cannot be used like ‘Inputter (form)’ as that may imply another version somewhere, and would look wrong with ‘Form-group (form)’ for example. So form type components would only rely on colour change and that feels like it should belong to the Component family, so tried a darker shade but this isn’t very explicit as only seen in isolation...

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/e924056c-c770-40be-a4e1-422ad2950114)


### Concept 2: Use different colour badges on the ‘Component’ Teal background.

This addresses the issues in Concept 1 but would rely on having the badge element of our docs up and working.

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/c5bc6e1a-51a4-4f9a-a124-d4f8b66728fa)

### Concept 3?: Utilise another Hue  
Using green to create a stronger difference but essentially the same technique as Concept 1

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/9b075a1e-5aee-4134-a7b1-5b7aaf7b10a5)


![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/4ff4a6e8-3003-4e2f-91af-53adf6a5f7d4)

**Comment by RobTobias123** [comment]
We can also see simulated here that if we were to go with concept 3, why it would be important to have "deprecated" written quite clearly to help distinguish the red/green for those who are colour blind with protanopia/protanomaly (a red/green confusion):

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/c50811db-73d2-44a8-8050-93d0c5e8baa9)

**Comment by RobTobias123** [comment]
Following this morning's stand-up, I agree with Ben that the masthead colour assignation should only apply to each main section of the Docs site and that we shouldn't assign different colours for each of the Component sub-sections. 

That is...
**All** Components (including Form and Deprecated) should remain 'Teal'. 
Experiences = 'Blue' (these are not 'components' so good to differentiate)
Foundations = 'Orange'
Patterns = 'Purple'
Page types = 'Magenta'

This keeps things simpler too.

**Comment by andij** [comment]
Here's the PR for the masthead

- #362
