### ISSUE TITLE
Homepage - Signpost links

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#365]
## Outcome

The homepage has the Signpost links

## Scope

- [x] Organise the layout for the Homepage
- [x] Include the signpost links
- [x] Styling for the signpost links

**Comment by andij** [comment]
Discussed the approach to the homepage and we decided to create another PR:

- #376

This PR has been merged and the PR above has been closed.

**Comment by RobTobias123** [comment]
Updated styling direction and layout suggestion for homepage reference:

https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=519%3A29089&mode=design&t=LxpzGNF4As2T2x1L-1
