### ISSUE TITLE
Content - Guidance - Tokens

### ISSUE THREAD

**Issue by MekalaNagarajan-Centrica** [centrica-engineering/nucleus-docs#366]
## Outcome

To create content page to display all foundation tokens from Nucleus.

### Scope
- [x] Page layout and styles
- [x] Colours
   - [x] Primary
   - [x] Secondary
   - [x] Greyscale
   - [x] System
- [x] Border https://github.com/centrica-engineering/nucleus-docs/pull/360
   - [x] Radius
   - [x] Width
- [x] Typography

**Comment by RobTobias123** [comment]
Page layout and styles suggested for the Tokens page can be found here (Figma) with annotations. https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=428%3A6545&mode=design&t=txUJLLaAp2dyn9Ww-1

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/68829a40-11b1-46cf-9de3-aef9726cbd69)

**Comment by andij** [comment]
In this PR I've laid out the swatch, name, value, token horizontally. (I've not considered the responsive design yet)
 
- #386 

Preview: https://feature-tokens-styles.nucleus-docs.pages.dev/guidelines/tokens/

**Comment by andij** [comment]
This PR I've styled the tokens in the same `spec-list` style that we use for the component specification.

- #411 

Preview: https://content-tokens-typography.nucleus-docs.pages.dev/guidelines/tokens/#typography
