### ISSUE TITLE
Footer - Improve the language

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#369]
Take a look at the current iteration of the Footer in our Astro docs and attempt to improve the language by making it more friendly and including a link for those who don't have (or possibly don't want) a GitHub account.

**Comment by RobTobias123** [comment]
Currently, we are displaying the following:
<img width="812" alt="Screenshot 2024-02-06 at 15 57 39" src="https://github.com/centrica-engineering/nucleus-docs/assets/78355810/1dc849c8-b29e-462c-bafd-338b66740e57">

The issue here is that all the links in the bullet list go to GitHub. My suggestion is to take the 'Report the content issue' link and change that to a non-GitHub way of reporting an issue - perhaps a link to our Teams channel (although that's not available to the public?) feel free to suggest other ways that may be more suitable. 

The language also could be perceived as a little abrupt instead of 'concise' as intended. Perhaps, we need to add a bit more 'fluffiness' and be descriptive, to get people to engage.

Here's my suggestion: 
"
### Found a problem with the content on this page? 
Here are some ways you can help:

[Suggest an edit](https://github.com/centrica-engineering/nucleus-docs/edit/astro-docs/src/content/docs/guidelines/tokens.mdx) [eg. GitHub direct edit link to page]
If you spot an issue, you can propose changes directly on GitHub. Your input matters!

[Report a content issue](https://github.com/centrica-engineering/nucleus-docs/edit/astro-docs/src/content/docs/guidelines/tokens.mdx) [Teams channel link?]
If something doesn’t look right, let us know. We appreciate your help in keeping our content accurate and helpful.

[View this page on GitHub](https://github.com/centrica-engineering/nucleus-docs/blob/astro-docs/src/content/docs/guidelines/tokens.mdx) [GitHub link to page with the File directory LHS view]
See this and every page in the Nucleus Docs on GitHub.

Want to get more involved with Nucleus Docs? 
[Learn how to contribute](#) and be part of our growing community. 🌟"

The last 'contribute' link would need to go to a page similar to the current docs pages Contribute to Nucleus, Our process etc... (Please add any thoughts to this idea here).

**Comment by andij** [comment]
- https://github.com/centrica-engineering/nucleus-docs/pull/378

**Comment by RobTobias123** [comment]
Reviewed.
