### ISSUE TITLE
Style the headings in the LHS

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#373]
### Outcome
Defined style for LHS nav categories and sub-categories that is distinguishable from the page links and themselves.

### Scope

- [x] Assess what we have
- [x] Gain further understanding of expectations for this (when raised by Ben in stand-up 6 Feb)
- [x] Provide visuals and values for intent
- [x] Test and check it meets requirements

**Comment by RobTobias123** [comment]
Visual example in isolation along with typography spec of the intended styling - note the character spacing and colour along with indentation and chevron, visually distinguish the categories from the usual page links they contain.

https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=595%3A27627&mode=design&t=ZPU8QaqOxpUjPLps-1

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/27380730-f782-4ed1-8968-cb2794230724)

**Comment by RobTobias123** [comment]
WCAG contrast compliant...

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/156435c8-f3e7-4e30-8b93-f58c1cbeb323)

**Comment by andij** [comment]
- #475
