### ISSUE TITLE
Footer - define the fun overun

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#383]
### Outcome
A unique and fun footer background for Nucleus Docs that appears when the footer 'edit links' section is scrolled past. (To replace the existing borrowed placeholder)

### Scope

- [x] Investigate concepts 
- [ ] Develop best one to be usable
- [ ] Implement

**Comment by RobTobias123** [comment]
3 concepts were explored; 

a tiled 'scale' approach of a duplicated and tesalting part of the Nucleus Logo
a Gratuitous Space Invader (+ variations)
a masthead illustration tiled pattern

**Comment by RobTobias123** [comment]
Link to the explorations:

https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=290%3A5503&mode=design&t=SpdB59P0efZOhOdg-1

**Comment by RobTobias123** [comment]
There may potentially be some issue with the complexity of the SVGs working in the CSS background. Drew is investigating.

**Comment by jholt1** [comment]
🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻
🏻🏾🏾🏻🏾🏾🏾🏾🏾🏾🏻🏾🏾🏻🏻🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻
🏻🏾🏾🏾🏽🏾🏾🏾🏾🏽🏾🏾🏾🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻🏻🏻🏻🏻🏻
🏻🏻🏾🏽🏾🏾🏾🏾🏾🏾🏽🏾🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻🏻🏻🏻
🏻🏻🏻🏿🏿🏾🏾🏾🏾🏿🏿🏾🏾🏾🏻🏻🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻🏻🏻
🏻🏻🏾🏽🏿🏾🏾🏾🏾🏿🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻🏻
🏻🏾🏼🏽🏽🏾🏾🏾🏾🏽🏽🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻
🏾🏼🏼🏾🏽🏼🏿🏿🏼🏽🏾🏼🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻
🏾🏼🏾🏼🏻🏻🏿🏿🏻🏻🏼🏾🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻
🏾🏼🏾🏼🏻🏻🏻🏻🏻🏻🏼🏾🏼🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻
🏾🏼🏼🏾🏾🏾🏾🏾🏾🏾🏾🏼🏼🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻
🏻🏾🏼🏼🏼🏼🏼🏼🏼🏼🏼🏼🏼🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻
🏻🏾🏼🏼🏼🏼🏼🏼🏼🏼🏼🏼🏼🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻🏻
🏻🏾🏼🏼🏻🏻🏻🏻🏻🏻🏻🏼🏼🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻
🏻🏻🏾🏼🏼🏻🏻🏻🏻🏻🏼🏼🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻
🏻🏻🏻🏾🏼🏼🏻🏻🏻🏻🏼🏼🏽🏽🏾🏽🏽🏽🏾🏾🏾🏽🏽🏾🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾
🏻🏻🏻🏻🏾🏼🏼🏻🏻🏻🏼🏽🏽🏽🏽🏽🏽🏽🏽🏽🏽🏽🏽🏾🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾
🏻🏻🏻🏻🏾🏼🏼🏻🏻🏻🏼🏼🏽🏽🏽🏼🏼🏼🏽🏽🏽🏼🏼🏾🏾🏽🏽🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾
🏻🏻🏻🏻🏾🏼🏼🏼🏼🏼🏼🏾🏽🏽🏽🏾🏾🏾🏼🏼🏼🏾🏾🏻🏻🏾🏾🏽🏽🏽🏾🏾🏾🏾🏾🏾🏾🏻
🏻🏾🏾🏾🏾🏾🏾🏼🏼🏼🏾🏾🏾🏾🏾🏻🏻🏻🏾🏾🏾🏻🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏾🏾🏾🏾🏾🏻
🏾🏽🏽🏽🏾🏾🏾🏾🏾🏾🏽🏽🏾🏾🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏾🏽🏽🏽🏾🏾🏾🏾🏾🏾🏾🏻
🏻🏾🏾🏾🏾🏻🏻🏻🏻🏾🏾🏾🏾🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏾🏾🏾🏾🏻🏾🏾🏾🏾🏾🏻
🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏻🏻
🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏾🏾🏻🏻🏻
🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏻🏾🏾🏾🏾🏾🏾🏻🏻🏻🏻🏻

**Comment by jholt1** [comment]
```
                                          ▓▓▓▓▓▓▓▓▓▓                        
  ▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓                    
  ▓▓▓▓▓▓▒▒▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓                  
    ▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓              
      ████▓▓▓▓▓▓▓▓████▓▓▓▓▓▓    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓            
    ▓▓▒▒██▓▓▓▓▓▓▓▓██▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓          
  ▓▓░░▒▒▒▒▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓        
▓▓░░░░▓▓▒▒░░████░░▒▒▓▓░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓        
▓▓░░▓▓░░    ████    ░░▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓        
▓▓░░▓▓░░            ░░▓▓░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      
▓▓░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      
  ▓▓░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      
  ▓▓░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓    
  ▓▓░░░░              ░░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  
    ▓▓░░░░          ░░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  
      ▓▓░░░░        ░░░░▒▒▒▒▓▓▒▒▒▒▒▒▓▓▓▓▓▓▒▒▒▒▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
        ▓▓░░░░      ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
        ▓▓░░░░      ░░░░▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒░░░░▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
        ▓▓░░░░░░░░░░░░▓▓▒▒▒▒▒▒▓▓▓▓▓▓░░░░░░▓▓▓▓    ▓▓▓▓▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓  
  ▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░▓▓▓▓▓▓▓▓▓▓      ▓▓▓▓▓▓            ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  
▓▓▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓                        ▓▓▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓  
  ▓▓▓▓▓▓▓▓        ▓▓▓▓▓▓▓▓                            ▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓  
                                                              ▓▓▓▓▓▓▓▓▓▓    
                                                        ▓▓▓▓▓▓▓▓▓▓▓▓▓▓      
                                                      ▓▓▓▓▓▓▓▓▓▓▓▓          
```

**Comment by andij** [comment]
Closing this ticket, we can refer to the ideas in here if / when we want to pick this up again.
