### ISSUE TITLE
Homepage - blog post

### ISSUE THREAD

**Issue by MekalaNagarajan-Centrica** [centrica-engineering/nucleus-docs#419]
## Outcome
To display nucleus blog posts in docs homepage.

### Scope
- [ ] Update blog rss feed schema in blog repo. https://github.com/centrica-engineering/nucleus-blog/issues/119
- [ ] Read rss feed https://github.com/centrica-engineering/nucleus-docs/issues/461
- [x] Blogs card component
- [x] Layout and styling

**Comment by andij** [comment]
- PR for including the image tag in the RSS feed https://github.com/centrica-engineering/nucleus-blog/pull/117

**Comment by MekalaNagarajan-Centrica** [comment]
Blog post in docs homepage PR https://github.com/centrica-engineering/nucleus-docs/pull/428

**Comment by MekalaNagarajan-Centrica** [comment]
Rss feed updation is moved to ticket https://github.com/centrica-engineering/nucleus-blog/issues/119
Using the Feed https://github.com/centrica-engineering/nucleus-docs/issues/461
