### ISSUE TITLE
New docs beta release

### ISSUE THREAD

**Issue by PtitBen** [centrica-engineering/nucleus-docs#464]
## Outcome
We have a beta version of the new docs released and available for our users to try.

### Release
- [x] Get the latest version of the new docs in production behind the domain beta.nucleus.design

### Advertise and and lead users to the beta
- [x] add banner on legacy docs #466
- [ ] add default story on storybook
- [x] draft and post announcement

**Comment by RobTobias123** [comment]
Draft annnouncement for Teams channel:

New Beta Release: Nucleus Docs Platform v.3.0
🔗 Try It Out: Explore the [Beta release of Nucleus Docs v.3.0](https://beta.nucleus.design/) here.

We’re thrilled to announce the latest version of Nucleus Docs, packed with exciting features and enhancements. Here’s what you can expect:

**Live Examples:** Dive into interactive examples directly within the documentation. Experience Nucleus in action and learn faster.

**Configuration Made Easy:** Effortlessly configure Nucleus component examples to suit your needs. Whether you’re a developer, designer, or content manager, our configurator feature helps you customise your experience based on available options.

**Improved User Interface:** Say hello to a user-tested, more usable UI. Navigating Nucleus has never been this delightful.

**Comment by RobTobias123** [comment]
Here's a draft 'one-liner' announcement for displaying on the existing docs banner - let me know if too long or if you want to change anything?... 
 
**New Beta Release:** Nucleus Docs v.3.0 — packed with live examples, an easy-to-use configurator, and an improved UI. Explore a wealth of information and specifications. [Try it out here](https://beta.nucleus.design/).

**Comment by andij** [comment]
- I have a PR for the Docusaurus banner: https://github.com/centrica-engineering/nucleus-docs/pull/466

But... Currently I'm unable to get my localhost running, even though I've tried to sort it. Mekala is helping to resolve it.

And, as far as I can see, my PR won't build a preview.

**Comment by andij** [comment]
> Here's a draft 'one-liner' announcement for displaying on the existing docs banner - let me know if too long or if you want to change anything?...
> 
> **New Beta Release:** Nucleus Docs v.3.0 — packed with live examples, an easy-to-use configurator, and an improved UI. Explore a wealth of information and specifications. [Try it out here](https://beta.nucleus.design/).

Can I suggest a change:

[**Beta Release:** Nucleus Docs v.3.0](https://beta.nucleus.design/) — packed with live examples, an easy-to-use configurator, and an improved UI. Explore a wealth of information and specifications.

**Comment by andij** [comment]
For `ns-skyline` on the current Docs homepage we need a little bit more content as it's a heading and a paragraph.

Suggestion: https://playground.nucleus.design/#project=c850a1a2-8e3b-45d7-a9b0-3e196f77e006

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/28779/5705aa1e-71f8-49df-b5fa-d04277516368)

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/28779/1ebfa3ab-ae49-41b5-9381-5cfc8acb4bf4)

**Comment by RobTobias123** [comment]
Can I also suggest that we re-order words to 'Nucleus Docs v3.0' instead of leading with 'v3.0 of the...'?

> For `ns-skyline` on the current Docs homepage we need a little bit more content as it's a heading and a paragraph.
>

**Comment by RobTobias123** [comment]
On the existing docs banner, it might be beneficial to provide affirmation that the 'Old docs' will not be switched off for some time yet.

Maybe....Rest assured, the old version will remain available for some time.

**Comment by andij** [comment]
We just sent out the announcement in the General channel. 🎉

And published the aanouncementBar in the existing Docs. We didn't use an `ns-skyline` as the announcementBar was also present on the homepage.

**Comment by MekalaNagarajan-Centrica** [comment]
An idea for adding a announcement banner in all stories https://github.com/ConnectedHomes/nucleus/pull/3371

**Comment by PtitBen** [comment]
I like both solutions.
Mekala is going to try a skyline instead of highlighter.

I would cut down the content on the default story from Drew's PR to keep it short and straight to the call to action.

**Comment by andij** [comment]
Closing this ticket as the two outstanding items are:

- #478 
- #479
