### ISSUE TITLE
404 helpful links

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#465]
### Outcome
An update Astro 404 page that contains links to help users recover from perhpas an 'old docs' bookmark link they clicked on expecting to go there. 

### Scope

- [x] Define what those links should be. (Intro, component, guideline, page types, patterns perhaps?)
- [x] Design Layout
- [x] Locate 404 page in astro-docs and update to include helpful links to sections of the New docs.
- [x] Refine content, links and layout options to best effect

**Comment by RobTobias123** [comment]
We discussed as a team the possibility and technicalities of providing links to a new page based on the obsolete URL that someone may have bookmarked. We will look at providing the specific old URL in the playback saying it can't be found with suggestions/signpost links to areas of potential interest.

**Comment by andij** [comment]
I've created a PR to include `404.mdx`, which is the default way Starlight presents this page.

- PR: https://github.com/centrica-engineering/nucleus-docs/pull/489

Preview: https://feature-404-page.nucleus-docs.pages.dev/my/old/bookmark

**Comment by RobTobias123** [comment]
Added content to the PR https://github.com/centrica-engineering/nucleus-docs/pull/489

Appended design intention to page layout specified above. Ready for review.

**Comment by RobTobias123** [comment]
Just an idea I had to make it a little fun - 404 logo and humorous heading.

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/ada8c105-c557-41a0-b872-17d778f1336e)

**Comment by RobTobias123** [comment]
Feedback link needs the 'external' icon adding.

**Comment by andij** [comment]
The 'namespace' and the masthead SVG are populated by taking information from the URL, as there's no 'slug', these are empty.

To add content in the `namespace` and to populate the SVG it will require additional work.

If it's important to provide additional clarity, consider changing the heading from 'Maybe the dog ate it?" to 'Error 404' (However, I think 'Page not found' works well enough.)

The Feedback link is present in the RHS navigation. I'd suggest that it's omitted from the list.

**Comment by RobTobias123** [comment]
Can we remove the masthead then? This page is not part of the categories so it's not relevant, and if we can't populate it due to URL slug, I question its necessity. Instead we can just retain the existing 404 image and replace 'Maybe the dog ate it' with Page not found. That would be visually clearer. Is that feasible?

**Comment by andij** [comment]
There are other options yeah.

We can use a Starlight template which will not display the masthead. However, it will also remove the left and right navigation. It's called the `splash` template and is designed for landing pages without sidebars which is what is used by default.
Example: https://beta.nucleus.design/show/me/the/404

I believe that having the LHS navigation on the 404 page is valuable.

It's also possible to disable the 404 page and create our own custom 404 page: https://starlight.astro.build/guides/customization/#disabling-the-default-404-page

If we were to include an image like the one you have created, please consider how it works in dark mode.

For simplicity's sake, my preference would be to keep what we have done already, refine the content to suit the needs of the page and accept that the masthead doesn't have a 'namespace' or an SVG.

**Comment by RobTobias123** [comment]
Thank you, Drew. Unfortunately, I find the last option to be somewhat of a compromise, and it may not meet the high standard we’re aiming for (there’s no benefit in displaying broken content). I’d like us to explore the first option you mentioned, as it aligns more closely with my initial design vision. While I understand the value you place on the left-hand navigation, I believe we can address that by including a set of carefully curated links on the page to help users get started (which might even simplify the decision-making process). Regarding the image in dark mode, we can either create a dedicated dark mode version or maintain a solid white background for the image, similar to what we do for CG images.

**Comment by RobTobias123** [comment]
Ok, I've tried adjusting things to get that working but it's pretty clunky and need some dev expertise on this please. 

404 image was reworked to use Teal-400 (like the word Docs in the header) so it works well on both light and dark bgrds.

I've made the title H1 in the content instead of large default style from front-matter. 

I have not been able to determine why the Announcement bar is not stretching to 100% width bit other than it appears to be predefined somewhere at a around 745px. I suspect this is because of the div and location of the element in the template. It may be worth comparing to Home page to understand the difference in code here. 

I am unable to control the space above and below the image nor control the left/centre alignment it responds to. 

I cannot get the external icon after feedback to stay in line with the link either. 

Please advise if you know of something we can try?



![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/fa13fa17-2337-4244-b645-a0ce66fb8ae5)


![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/41dd5233-4283-4e91-9901-068027d86623)

**Comment by RobTobias123** [comment]
Mekala has fixed the issues  - I will review this.

**Comment by andij** [comment]
I've made a few changes to the markup of the 404 page and some styling.

Hopefully this latest iteration will be good to go!

- #489
