### ISSUE TITLE
Dark mode colour assessment

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#467]
### Outcome

A refined and full set of Dark mode colours and directions that work across all applications of it. Tested and ready for launch. Currently, there are some clashes between different astro components for eg. Mastheads and Asides share colours but have different requirements.

### Scope

- [x] Consider new saturation and Lightness values based on the given Hues 
- [x] Assess impact 
- [x] Test for WCAG contrast compliance
- [x] Adjust values as required

### Notes

- Switch light/dark toggle back on for this branch/work
- Assess current set-up - use test.mdx for visual ref.

**Comment by andij** [comment]
The first area that we can address is to understand the different combinations of content that we expect in the Asides.

- I've raised a PR for this: https://github.com/centrica-engineering/nucleus-docs/pull/486

Preview: https://feature-dark-mode-a11y.nucleus-docs.pages.dev/components/ns-test/#asides

**Comment by RobTobias123** [comment]
Set up an area in Figma for assessing (WIP)...
https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=606%3A28408&mode=design&t=NUg9tVpTJ3mO1Jtp-1

**Comment by RobTobias123** [comment]
### Asides PR and colours assessed. 

My suggestions for changes and reasons here:

https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=0%3A1&mode=design&t=NUg9tVpTJ3mO1Jtp-1

#### FINE AS IT IS:

- Paragraph style Hyperlinks are inheriting heading colours  - Checked for contrast compliance - all ok on aside backgrounds in both light and dark themes.  - Happy with this behaviour
- Paragraph text and Backtick text is not as originally specified (using Starlight text values?) but is is close and conforming.   - Happy to leave as is or change to Navy. 

#### REQUIRES CHANGE + SUGGESTIONS:
 
- Backtick style Hyperlinks are inheriting heading colours - Not conforming as background is too tonally similar. 
- Suggestion: Keep text and hyperlink colours the same but change background-colour to : 
TEAL-800
HSL 202/40/16

All pass WCAG contrast then...

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/759bd3d2-2f80-495c-b993-396e626ceaa8)

**Comment by RobTobias123** [comment]
Looking at the tabs - it would be ideal if they used the proposed colours from the palette. This provides a better contrast between a highlight and the track and also is more consistent with the use of Accent colour. 

https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=619%3A27575&mode=design&t=pb3ElDChD7M5gneK-1

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/81f47b69-5cc5-4c47-a36e-9be92cbde69e)

**Comment by RobTobias123** [comment]
Form elements currently being reviewed and changes being suggested at https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=633%3A27629&mode=design&t=wJatGc2xRvcCsvP0-1

**Comment by RobTobias123** [comment]
Added further example visuals and values to form elements. 
https://www.figma.com/file/wyuLUEt3qm01mR8E6Wm2Pf/Nucleus-Docs-exploration---engaging-and-interactive?type=design&node-id=633%3A27629&mode=design&t=wJatGc2xRvcCsvP0-1

**Comment by RobTobias123** [comment]
Putting on hold temporarily whilst prioritising other work on the docs.

**Comment by RobTobias123** [comment]
It was discussed yesterday that the order of the main 4 signposts read order on the home page does not match the read order of the same groups in the LHS nav menu. This should be aligned so that it is familiar to the user.

**Comment by RobTobias123** [comment]
Explored and defined more specifics of the backticks design with Drew and agreed on best approach to implement that includes a subtle border and variable background colour dependent on mode.

**Comment by RobTobias123** [comment]
Also included nsx blue values as this affects the Mastheads in the same way too. 

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/3d188627-c584-454d-b127-0deffd59fd8a)

**Comment by andij** [comment]
I've updated the PR to reflect these updated colours

- In this PR: https://github.com/centrica-engineering/nucleus-docs/pull/486

In order to release this we will raise another ticket related to bringing the dark mode into the Configurator.
