### ISSUE TITLE
Populate ns-timeline-event page

### ISSUE THREAD

**Issue by MekalaNagarajan-Centrica** [centrica-engineering/nucleus-docs#476]
## Outcome
To populate timeline-event page manual content.

### Status
- [x] Examples for all different types.
- [x] Content guidance
- [x] Link timeline and timeline-event pages.

**Comment by RobTobias123** [comment]
2nd ns-timeline (full) webp iteration labels A-E with shorter pointers where possible, labels all on top, label E now includes the additional content card, as requested.

[ns-timeline content-guidance-standard - NEW.webp.zip](https://github.com/centrica-engineering/nucleus-docs/files/14493301/ns-timeline.content-guidance-standard.-.NEW.webp.zip)

**Comment by RobTobias123** [comment]
I've separated the different timeline-event status as you requested but I was thinking do we even need pending or in progress to show any difference other than status? I've labelled what I could understand and re-ordered from event specifics in the table to the  left so you can see which would belong to each with new letter.Please let me know how you would like to proceed with this?

<img width="1209" alt="Screenshot 2024-03-05 at 10 50 25" src="https://github.com/centrica-engineering/nucleus-docs/assets/78355810/28141016-82a2-4386-a656-7dc6e1678f50">

**Comment by RobTobias123** [comment]
Following feedback, events for in progress and completed states are not necessary so removed, and timestamp label E starts relative to the separate part in this webp:

[ns-timeline-event - All parts - NEW.webp.zip](https://github.com/centrica-engineering/nucleus-docs/files/14494250/ns-timeline-event.-.All.parts.-.NEW.webp.zip)

<img width="1249" alt="Screenshot 2024-03-05 at 11 06 15" src="https://github.com/centrica-engineering/nucleus-docs/assets/78355810/b75196ec-1383-40d4-9aae-3bdf749a122f">
