### ISSUE TITLE
Storybook - Introduction story for Docs v3.0

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#478]
## Outcome

Storybook to have a default introduction page with a simple message and call to action for Nucleus Docs v3.0

## Scope

- [x] Create 'introduction' story
- [x] Set this page as the default story
- [x] Include component choice and content

## Reference

- #464

**Comment by andij** [comment]
- PR: https://github.com/ConnectedHomes/nucleus/pull/3372

**Comment by andij** [comment]
- PR: https://github.com/ConnectedHomes/nucleus/pull/3372

![image](https://github.com/centrica-engineering/nucleus-docs/assets/28779/fcb7c1f0-4315-4765-a582-ccc9ec9f5403)

Preview: https://63ea3fa8c3721b415537bccc-vmrnzdjuoy.chromatic.com/?path=/story/about-nucleus-docs-v3-0--nucleus-docs-v-3

**Comment by andij** [comment]
- PR: https://github.com/ConnectedHomes/nucleus/pull/3372

**Comment by PraveenAsokan** [comment]
Released in nucleus v3.4.1.
