### ISSUE TITLE
Storybook - announcement banner

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#479]
## Outcome

A banner at the top of all pages in Storybook announcing the launch of Nucleus Docs v3.0

## Scope

- [x] Add a banner at the top of all pages
- [x] Include design and choice of content

## Reference

- #464

**Comment by andij** [comment]
- PR: https://github.com/ConnectedHomes/nucleus/pull/3371

**Comment by RobTobias123** [comment]
Here's a suggestion using Nucleus styles and content as the current docs banner as discussed this morning (Blue bgrd ties in with the Nucleus Docs banner message so retains consistency, grey-light alternative also):

<img width="799" alt="Screenshot 2024-03-04 at 12 27 20" src="https://github.com/centrica-engineering/nucleus-docs/assets/78355810/5353f4c2-2c7d-493d-aed6-68d4cc35aacd">

<img width="797" alt="Screenshot 2024-03-04 at 12 27 30" src="https://github.com/centrica-engineering/nucleus-docs/assets/78355810/88315039-8ea4-4458-94ac-2ce653967ef5">


https://www.figma.com/file/FzsdCwuZQi1yvYpjL3xZUW/3372---Storybook-announcements?type=design&node-id=1%3A222&mode=design&t=tlilVlR6YWtSelFF-1

**Comment by andij** [comment]
I'd like to propose that we have a white banner with the same bottom border as the Storybook interface.

Like this:

![image](https://github.com/centrica-engineering/nucleus-docs/assets/28779/32fc14af-33e3-4ae3-a666-9c6219a4e6e4)

Rather than blue:

![image](https://github.com/centrica-engineering/nucleus-docs/assets/28779/3c22ae53-c2fc-45b6-9411-33c66992982f)

**Comment by PraveenAsokan** [comment]
Released in nucleus v3.4.1.
