### ISSUE TITLE
Content - Types purpose

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#531]
### Outcome
The purpose described for each type, state and variation of each component example.

### Scope
Review/improve:

- [x] ns-action-link - PR: https://github.com/centrica-engineering/nucleus-docs/pull/653
- [x] ns-alert (exists at https://nucleus.design/components/ns-alert/ )
- [x] ns-card (exists at https://nucleus.design/components/ns-card/)
- [x] ns-cta (https://nucleus.design/components/ns-cta/)
- [x] ns-datepicker - PR: https://github.com/centrica-engineering/nucleus-docs/pull/654
- [x] ns-download - PR: https://github.com/centrica-engineering/nucleus-docs/pull/655 and https://github.com/centrica-engineering/nucleus-docs/pull/659
- [x] ns-expander - PR: https://github.com/centrica-engineering/nucleus-docs/pull/657
- [x] ns-header (exists at https://nucleus.design/components/ns-header/)
- [x] ns-icon - #533 
- [x] ns-illustration - #533 
- [x] ns-image (exists at https://nucleus.design/components/ns-image/)
- [x] ns-inputter (not necessary - self-explanatory)
- [x] ns-landmark (exists at https://nucleus.design/components/ns-landmark/)
- [x] ns-password - PR: https://github.com/centrica-engineering/nucleus-docs/pull/658
- [x] ns-selector - PR: https://github.com/centrica-engineering/nucleus-docs/pull/660
- [x] ns-table - PR: https://github.com/centrica-engineering/nucleus-docs/pull/661
- [x] ns-timeline - PR: https://github.com/centrica-engineering/nucleus-docs/pull/662
- [x] nsx-address-selector (not necessary - self-explanatory)
- [x] nsx-header (not necessary - self-explanatory, although could perhaps benefit from default being shown at 50%)
- [x] nsx-marketing-consent - PR: https://github.com/centrica-engineering/nucleus-docs/pull/663
- [x] nsx-product-card-overview - (exists at https://nucleus.design/components/nsx-product-card-overview/)

**Comment by RobTobias123** [comment]
As discussed this morning, I've opened this ticket to use as a place to address the Docs feedback received from Scottie on the Docs Feedback form:
<img width="929" alt="Screenshot 2024-03-20 at 10 22 24" src="https://github.com/centrica-engineering/nucleus-docs/assets/78355810/a08c1dd1-7df4-49af-957e-44d48176ef6f">

Actions to address this will be to add a link higher up the page for visibility/hierarchy that links to the visual lists in the Guidelines Assets page, to be added to the ns-icon and ns-illustration components pages.

**Comment by RobTobias123** [comment]
Added prominent reciprocal links for illustrations icons and assets.

PR for review please:
https://github.com/centrica-engineering/nucleus-docs/pull/533

**Comment by RobTobias123** [comment]
Using branch of `epic/examples-purpose` as the base for the individual PRs.

**Comment by andij** [comment]
- Here it the Epic PR: https://github.com/centrica-engineering/nucleus-docs/pull/656

**Comment by RobTobias123** [comment]
Looking at ns-inputter type examples - they are all quite self-explanatory to me. Would it be unnecessary to add descriptions here? I feel most people would understand and be familiar with what their purpose is.

**Comment by RobTobias123** [comment]
Updated and resolved comments on #653 and #654

**Comment by RobTobias123** [comment]
Updated #657

**Comment by RobTobias123** [comment]
Merged the approved #658

**Comment by RobTobias123** [comment]
Updated #660

**Comment by RobTobias123** [comment]
Merged the approved #661

**Comment by RobTobias123** [comment]
Merged the approved #662

**Comment by RobTobias123** [comment]
Updated #663

**Comment by RobTobias123** [comment]
All approved and merged. Closing as completed.

**Comment by andij** [comment]
I'm reopening this ticket as the epic PR for this ticket has yet to be reviewed:

- https://github.com/centrica-engineering/nucleus-docs/pull/656

**Comment by RobTobias123** [comment]
Committed and slightly tweaked* some of Mekala's suggestions on the Epic branch. (*Added 'articles' like 'the' where necessary). All resolved and awaiting final approval.

**Comment by RobTobias123** [comment]
Merged this now it has been approved.

**Comment by RobTobias123** [comment]
Closing as completed and epic approved and merged.
