### ISSUE TITLE
Summarisation button

### ISSUE THREAD

**Issue by jholt1** [centrica-engineering/nucleus-docs#602]
## Outcome

To get a summary of the documentation for that component.

## Scope

- [x] API for summarisation.
- [x] Summarisation button at the top of the page. 

## Worries

- It is AI generated and we don't know what it might say.
- Might mean they don't read the whole documentation.

## Benefits

- Forces us to structure the page correctly, in a readable manner.
- If an AI can summarise it well, then most people should be able to understand the documentation.
- Might mean that people find the right component quicker.

**Comment by RobTobias123** [comment]
I really like this idea, minor suggestions for visual improvement: 
Make icon similar in colour to the others.
On the label, just 'Summarise' - without the 'it' and exclamation. 
Can we make the results use UK English spelling instead?

**Comment by RobTobias123** [comment]
(Couldn't remember if it needed to be coloured or black for docs - here's both:
[icon-ai-sparkle-teal.svg.zip](https://github.com/centrica-engineering/nucleus-docs/files/15061683/icon-ai-sparkle-teal.svg.zip)
[icon-ai-sparkle.svg.zip](https://github.com/centrica-engineering/nucleus-docs/files/15061684/icon-ai-sparkle.svg.zip)
