### ISSUE TITLE
[ns-frame] Component documentation

### ISSUE THREAD

**Issue by MekalaNagarajan-Centrica** [centrica-engineering/nucleus-docs#643]
## Outcome

To add component documentation for `ns-frame` component.

## Scope

- [x] Description
- [x] Examples
- [x] Content guidance
  - [x] Match labels and content
  - [x] add label for header
  - [x] add content for search
  - [x] open account bubble on screenshot
  - [x] add label and content for account
- [x] Specification

Pull request:

- https://github.com/centrica-engineering/nucleus-docs/pull/619

**Comment by MekalaNagarajan-Centrica** [comment]
PR to revert ce json temp files https://github.com/centrica-engineering/nucleus-docs/pull/644

**Comment by RobTobias123** [comment]
I've updated the guidance image and labels to include an open account and search, plus added the copy in the key for those sections. Also, now using a bracket type label on the image to indicate the header section. PR #619  for review please.

**Comment by RobTobias123** [comment]
'Example' is included in the above but utilises different content. Whereas the guidance image is reflecting what is currently live. Should we update the Example to be the same or perhaps it doesn't matter as the frame is ok?
