### ISSUE TITLE
[Docs] Update content Guidance image for nsx-marketing-consent

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#714]
### Outcome

Updated content guidance image of nsx-marketing-consent to reflect the latest version seen in code with the new text and inline checkboxes (at wide VPs).

### Scope

- [x] Update CG image from Playground screenshot at standard size.
- [x] Save as Webp.
- [x] Update assets.
- [x] PR
- [x] Merge on approval

**Comment by RobTobias123** [comment]
PR for review please:

https://github.com/centrica-engineering/nucleus-docs/pull/715

**Comment by andij** [comment]
- Closing this ticket as PR #715 has been merged into #716
