### ISSUE TITLE
ns-scroller docs entry

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#722]
### Outcome
A Nucleus Docs page for the new ns-scroller component, with examples and content guidance etc.

### Scope

- [x] Branch - `feature/ns-scroller-docs`
- [x] Masthead SVG
- [x] Purpose one-liner
- [x] Overview content
- [x] HTML examples (placeholder now - add once built)
- [x] Guidance - Do/Don'ts
- [x] Guidance - Diagram (1280) and key
- [x] Implementation - Placement
- [x] Spec/Spec notes
- [x] Apply 'new' badge to LHS menu. 
- [x] Share iterations for feedback ad adjustment.
- [x] Merge on approval and coincide with release of code [#844](https://github.com/centrica-engineering/nucleus/issues/844)

**Comment by RobTobias123** [comment]
Work in progress... Feel free to comment/suggest...

https://github.com/centrica-engineering/nucleus-docs/pull/724

**Comment by RobTobias123** [comment]
HTML examples and automatically generated content yet to be configured as it is dependent on the completion of the component build in [#844](https://github.com/centrica-engineering/nucleus/issues/844)

**Comment by RobTobias123** [comment]
Added HTML examples that should format correctly on release of ns-scroller. Updated suggested content - some of which to be dynamically generated from the component.

PR for review/adding automated content to: https://github.com/centrica-engineering/nucleus-docs/pull/724

**Comment by RobTobias123** [comment]
Created and added labeled guidance image and updated key.

**Comment by PtitBen** [comment]
I've added a suggestion for the nesting of the component :)
