### ISSUE TITLE
[ns-panel] Add Inset information to docs page

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#737]
### Outcome
Inset type of ns-panel information included in componenets/ns-panel documentation

### Scope

- [x] update nucleus version to get JSDocs content
- [x] Content guidance + do/don't
- [x] Image?
- [x] HTML example

Branch: https://github.com/centrica-engineering/nucleus-docs/tree/origin-add-inset-panel
PR: https://github.com/centrica-engineering/nucleus-docs/pull/738

**Comment by RobTobias123** [comment]
Reference: https://github.com/centrica-engineering/nucleus/issues/903

**Comment by RobTobias123** [comment]
Branch created: `chore/add-inset-info-too-ns-panel`

**Comment by PtitBen** [comment]
Branch: https://github.com/centrica-engineering/nucleus-docs/tree/origin-add-inset-panel
PR: https://github.com/centrica-engineering/nucleus-docs/pull/738

**Comment by RobTobias123** [comment]
Looks good - PR approved
