### ISSUE TITLE
Exposing our blog on our Docs

### ISSUE THREAD

**Issue by PtitBen** [centrica-engineering/nucleus-docs#91]
## Issue / opportunity

Our blog can help push our PageRank up for search engines if it is linked from our main web presence: our documentation.

This might help us gain more exposure and have a bigger share of results for "nucleus design system" searches.

## Scope

- [ ] Documentation header nav
- [ ] Documentation footer
- [ ] Maybe even a lockup/card on the homepage?

**Comment by andij** [comment]
Closing as we have included the 4 blog posts on the Docs Hompage in v3.0
